### ISSUE TITLE
Package `is_simulation` or `is_this_reality` 

### ISSUE THREAD

**Issue by PhileasL** [robotique-ecam/cdfr#33]
Could be nice to create a function `is_simulation` or even `is_this_reality`  dans un package et l'utiliser partout pour detecter la simu. ARM64 will become more common in the future and this limits code duplication

_Originally posted by @3wnbr1 in https://github.com/robotique-ecam/cdfr/pull/31#discussion_r583181278_

**Comment by 3wnbr1** [comment]
Could be somekind of utils package
